In [1]:
import pandas as pd
import numpy as np

In [3]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Anushka\Downloads\placement_dataset.csv")

In [4]:
df.head() # checking  if dataset is loaded or not

,Student_ID,Gender,Age,Branch,CGPA,Tenth_Percentage,Twelfth_Percentage,Python,Java,SQL,...,Aptitude_Score,Projects,Internship,Certifications,LeetCode_Problems,Hackathons,Resume_Score,Placement_Readiness,Expected_Salary_LPA,Placement
0,1001,Female,21,BCA,8.25,61.0,70.5,Yes,Yes,Yes,...,5,1,Yes,4,101,5,96,72,8.0,Yes
1,1002,Female,20,BSc CS,8.03,90.8,60.2,Yes,No,No,...,4,3,Yes,2,176,4,98,70,7.8,Yes
2,1003,Female,23,BSc CS,7.48,64.7,95.0,Yes,No,No,...,6,0,Yes,6,51,3,100,78,8.5,Yes
3,1004,Male,20,BCA,9.09,66.2,73.5,No,Yes,Yes,...,9,5,Yes,5,166,0,100,87,9.2,Yes
4,1005,Female,22,BCA Data Science,7.23,62.5,94.7,No,Yes,No,...,5,5,No,5,299,3,97,73,8.1,Yes

In [5]:
df.shape

(1000, 25)

In [6]:
df.columns

Index(['Student_ID', 'Gender', 'Age', 'Branch', 'CGPA', 'Tenth_Percentage',
       'Twelfth_Percentage', 'Python', 'Java', 'SQL', 'Excel', 'PowerBI',
       'Tableau', 'Machine_Learning', 'Communication_Skill', 'Aptitude_Score',
       'Projects', 'Internship', 'Certifications', 'LeetCode_Problems',
       'Hackathons', 'Resume_Score', 'Placement_Readiness',
       'Expected_Salary_LPA', 'Placement'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student_ID           1000 non-null   int64
 1   Gender               1000 non-null   object
 2   Age                  1000 non-null   int64
 3   Branch               1000 non-null   object
 4   CGPA                 1000 non-null   float64
 5   Tenth_Percentage     1000 non-null   float64
 6   Twelfth_Percentage   1000 non-null   float64
 7   Python               1000 non-null   object
 8   Java                 1000 non-null   object
 9   SQL                  1000 non-null   object
 10  Excel                1000 non-null   object
 11  PowerBI              1000 non-null   object
 12  Tableau              1000 non-null   object
 13  Machine_Learning     1000 non-null   object
 14  Communication_Skill  1000 non-null   int64
 15  Aptitude_Score       1000 non-null   int64
 16  Projects             1000 non-null   int64
 17  Internship           1000 non-null   object
 18  Certifications       1000 non-null   int64
 19  LeetCode_Problems    1000 non-null   int64
 20  Hackathons           1000 non-null   int64
 21  Resume_Score         1000 non-null   int64
 22  Placement_Readiness  1000 non-null   int64
 23  Expected_Salary_LPA  1000 non-null   float64
 24  Placement            1000 non-null   object
dtypes: float64(4), int64(10), object(11)
memory usage: 195.4+ KB

In [8]:
df.isnull().sum() #checking for missing values

Student_ID             0
Gender                 0
Age                    0
Branch                 0
CGPA                   0
Tenth_Percentage       0
Twelfth_Percentage     0
Python                 0
Java                   0
SQL                    0
Excel                  0
PowerBI                0
Tableau                0
Machine_Learning       0
Communication_Skill    0
Aptitude_Score         0
Projects               0
Internship             0
Certifications         0
LeetCode_Problems      0
Hackathons             0
Resume_Score           0
Placement_Readiness    0
Expected_Salary_LPA    0
Placement              0
dtype: int64

In [9]:
df.duplicated().sum() # checking for duplicate rows

np.int64(0)

In [10]:
df.describe() # summary of all numerical columns

,Student_ID,Age,CGPA,Tenth_Percentage,Twelfth_Percentage,Communication_Skill,Aptitude_Score,Projects,Certifications,LeetCode_Problems,Hackathons,Resume_Score,Placement_Readiness,Expected_Salary_LPA
count,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0000
mean,1500.500000,21.995000,7.69609,79.066900,78.544900,7.093000,6.993000,3.102000,2.881000,156.030000,2.493000,93.014000,76.569000,8.3775
std,288.819436,1.419503,1.25530,10.904719,11.066474,1.971862,2.000738,1.997896,2.010194,86.283753,1.667553,9.358279,8.699938,0.7255
min,1001.000000,20.000000,5.51000,60.000000,60.000000,4.000000,4.000000,0.000000,0.000000,0.000000,0.000000,57.000000,46.000000,5.8000
25%,1250.750000,21.000000,6.63750,69.975000,68.975000,5.000000,5.000000,1.000000,1.000000,82.000000,1.000000,88.000000,72.000000,8.0000
50%,1500.500000,22.000000,7.80000,79.200000,78.100000,7.000000,7.000000,3.000000,3.000000,157.500000,2.000000,98.000000,78.000000,8.5000
75%,1750.250000,23.000000,8.75000,88.625000,88.000000,9.000000,9.000000,5.000000,5.000000,231.000000,4.000000,100.000000,84.000000,9.0000
max,2000.000000,24.000000,9.79000,97.900000,98.000000,10.000000,10.000000,6.000000,6.000000,300.000000,5.000000,100.000000,90.000000,9.5000

In [11]:
df.dtypes # checking data types

Student_ID               int64
Gender                  object
Age                      int64
Branch                  object
CGPA                   float64
Tenth_Percentage       float64
Twelfth_Percentage     float64
Python                  object
Java                    object
SQL                     object
Excel                   object
PowerBI                 object
Tableau                 object
Machine_Learning        object
Communication_Skill      int64
Aptitude_Score           int64
Projects                 int64
Internship              object
Certifications           int64
LeetCode_Problems        int64
Hackathons               int64
Resume_Score             int64
Placement_Readiness      int64
Expected_Salary_LPA    float64
Placement               object
dtype: object

In [12]:
yes_no_columns = [
    'Python', 'Java', 'SQL', 'Excel',
    'PowerBI', 'Tableau',
    'Machine_Learning',
    'Internship',
    'Placement'
]

for col in yes_no_columns:
    df[col] = df[col].map({'Yes': 1, 'No': 0})  #Encode Yes/No columns -- it will replace the yes-->1 and no-->0

In [13]:
df['Gender'] = df['Gender'].map({'Male':1, 'Female':0})

In [ ]:
 Why did we encode categorical data?

Machine learning algorithms work with numerical data. Since columns like Gender, Python, Internship, and Placement contained text values, we converted them into numerical values using mapping and Label Encoding so that the model could process them.

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le = LabelEncoder()

df['Branch'] = le.fit_transform(df['Branch'])

In [16]:
df.head()

,Student_ID,Gender,Age,Branch,CGPA,Tenth_Percentage,Twelfth_Percentage,Python,Java,SQL,...,Aptitude_Score,Projects,Internship,Certifications,LeetCode_Problems,Hackathons,Resume_Score,Placement_Readiness,Expected_Salary_LPA,Placement
0,1001,0,21,0,8.25,61.0,70.5,1,1,1,...,5,1,1,4,101,5,96,72,8.0,1
1,1002,0,20,2,8.03,90.8,60.2,1,0,0,...,4,3,1,2,176,4,98,70,7.8,1
2,1003,0,23,2,7.48,64.7,95.0,1,0,0,...,6,0,1,6,51,3,100,78,8.5,1
3,1004,1,20,0,9.09,66.2,73.5,0,1,1,...,9,5,1,5,166,0,100,87,9.2,1
4,1005,0,22,1,7.23,62.5,94.7,0,1,0,...,5,5,0,5,299,3,97,73,8.1,1

In [17]:
from sklearn.model_selection import train_test_split

In [19]:
X = df.drop("Placement", axis=1)
y = df["Placement"]

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [25]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

C:\Users\Anushka\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [26]:
y_pred = model.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [27]:
y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy * 100, "%")

Accuracy: 98.0 %

In [28]:
from sklearn.metrics import confusion_matrix   #Confusion Matrix

                                                     # Accuracy alone doesn't tell the whole story. We also want to know:

                                                          # How many students were correctly predicted as placed.
                                                          # How many were correctly predicted as not placed.
                                                           #How many predictions were incorrect
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[  8   4]
 [  0 188]]

In [29]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.67      0.80        12
           1       0.98      1.00      0.99       188

    accuracy                           0.98       200
   macro avg       0.99      0.83      0.89       200
weighted avg       0.98      0.98      0.98       200

In [ ]:
What is pickle?

pickle is a Python library used to save Python objects (such as a trained machine learning model) into a file.

In [30]:
import pickle
with open("placement_model.pkl", "wb") as file:
    pickle.dump(model, file)